# Generated by Django 4.1.3 on 2022-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500, unique=True),
        ),
    ]
